name: README Updater

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Running Main Script
        run: |
          pip install requests
          python main.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated profile with random comic."
          git push
